[project]
name = "pytorch"
version = "0.1.0"
description = "pytorch learning"
readme = "README.md"
authors = [
    { name = "tarun gupta", email = "taruneng12@gmail.com" }
]
requires-python = ">=3.12,<3.13"

dependencies = [
    "notebook>=7.6.2",
    "numpy>=2.5.3",
    "torch>=2.14.0",
]

[project.scripts]
pytorch = "pytorch:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
